
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 30 22:22:39 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Variable = 8;
  public static final int Multiplicacion = 5;
  public static final int Numero_Real = 7;
  public static final int Division = 6;
  public static final int ERROR = 9;
  public static final int EOF = 0;
  public static final int Suma = 3;
  public static final int error = 1;
  public static final int Igual = 2;
  public static final int Resta = 4;
}

